# Generated by Django 4.2.3 on 2023-08-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1024)),
                ('phone', models.CharField(max_length=512)),
                ('is_expire', models.BooleanField(default=False)),
                ('tries', models.SmallIntegerField(default=0)),
                ('extra', models.JSONField(default={})),
                ('step', models.CharField(max_length=26)),
                ('by', models.IntegerField(choices=[(1, 'By register'), (2, 'By login')])),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(default='50 000 uzs', max_length=123),
        ),
    ]
