# Generated by Django 4.2.3 on 2023-08-24 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_otp_alter_price_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Elektron pochtasi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='docs', verbose_name='rasm'),
        ),
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='SHifokor haqida qisqacha'),
        ),
        migrations.AlterField(
            model_name='user',
            name='prof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.professions', verbose_name='SHifokor Mutaxasisligi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='prosition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.position', verbose_name='SHifokor lavozimi'),
        ),
    ]
