# Generated by Django 4.2.3 on 2023-12-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_date_price_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': 'Servis',
                'verbose_name_plural': '2. Servislar',
            },
        ),
        migrations.RemoveField(
            model_name='price',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicedoc',
            name='service',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
