# Generated by Django 4.2.3 on 2023-08-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_email_alter_user_img_alter_user_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
