# Generated by Django 4.2.3 on 2023-12-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_price_doc_alter_kafedra_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafedra',
            name='about',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
