# Generated by Django 4.2.3 on 2023-09-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_spam_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='spam',
            name='isba',
            field=models.BooleanField(default=True),
        ),
    ]
