# Generated by Django 4.2.3 on 2024-01-08 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_kafedra_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kafedra',
            name='user',
        ),
        migrations.RemoveField(
            model_name='spam',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='kafedra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.kafedra'),
        ),
        migrations.DeleteModel(
            name='ServiceDoc',
        ),
    ]
