# Generated by Django 4.2.3 on 2023-09-14 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_spam_isba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spam',
            name='isba',
        ),
    ]
