# Generated by Django 4.2.3 on 2024-01-08 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_kafedra_user_remove_spam_user_user_kafedra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hindex', models.CharField(max_length=10)),
                ('citedby', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
