# Generated by Django 4.2.3 on 2023-09-14 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_is_spam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spam',
            old_name='is_active',
            new_name='active',
        ),
    ]
