# Generated by Django 4.2.3 on 2024-01-08 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_teacher_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_info',
            name='user',
        ),
        migrations.AddField(
            model_name='teacher_info',
            name='kafedra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.kafedra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher_info',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_info',
            name='citedby',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_info',
            name='hindex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_info',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
