# Generated by Django 4.2.3 on 2023-09-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_is_active_spam_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spam',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
