# Generated by Django 4.2.3 on 2023-09-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_spam_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spam',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
