# Generated by Django 4.2.3 on 2024-02-04 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_teacher_info_kafedra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher_info',
            name='citedby',
        ),
        migrations.RemoveField(
            model_name='teacher_info',
            name='hindex',
        ),
        migrations.RemoveField(
            model_name='teacher_info',
            name='year',
        ),
        migrations.AddField(
            model_name='teacher_info',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='teacher_info',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('value', models.CharField(blank=True, max_length=1000, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('links', models.CharField(blank=True, max_length=2000, null=True)),
                ('teacher_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.teacher_info')),
            ],
        ),
        migrations.CreateModel(
            name='Cited_by',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('citations', models.CharField(blank=True, max_length=10, null=True)),
                ('h_index', models.CharField(blank=True, max_length=10, null=True)),
                ('i10_index', models.CharField(blank=True, max_length=10, null=True)),
                ('since_2019c', models.CharField(blank=True, max_length=20, null=True)),
                ('since_2019h', models.CharField(blank=True, max_length=20, null=True)),
                ('since_2019h10', models.CharField(blank=True, max_length=20, null=True)),
                ('graph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.graph')),
                ('teacher_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.teacher_info')),
            ],
        ),
    ]
