# Generated by Django 4.2.3 on 2024-02-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_books_remove_teacher_info_citedby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
