# Generated by Django 4.2.3 on 2023-09-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_otp_created_servicedoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created',
            field=models.DateTimeField(auto_created=True, editable=False),
        ),
    ]
